### PR TITLE
Changes to Health Icon (Dynamic Icon Frames Support)

### PR DESCRIPTION
**Pull request by BeastlyGabi**
remains untested for now
old code bothered me in multiple ways and I hated the way I did it so I'm just rewriting it

idk what this engine uses for scripting necessarily but modifying the frame indexes should be as easy as calling `iconP1.animationMap.set(50, 4);` now, in this example `50` is health percentage, and 4 is frame number 4 on the image

I can't really test the changes at the moment because I can't compile the game and it's very late at night by the time I'm writing this so please help me out with testing these, it's kinda annoying not being able to test stuff

### CODE REVIEW

**Comment by Wither362** [comment]
😮

**Review by MemeHovy — COMMENTED** [review]
yoooo, this is sick! I’ll test the changes when I get back home this week

**Comment by MemeHovy** [comment]
but so far, I love these changes

**Comment by MemeHovy** [comment]
hey @BeastlyGabi can you do a favor and enable changes from maintainers? so I can assist you here

**Comment by MemeHovy** [comment]
nvm

**Comment by BeastlyGabi** [comment]
hold on

**Comment by BeastlyGabi** [comment]
image
oh it's already enabled, might be because its a draft

**Comment by MemeHovy** [comment]
> image
> oh it's already enabled, might be because its a draft

58D22C4D-5B70-4A8F-B9F1-8050BC3B10D7

same error @BeastlyGabi

**Comment by BeastlyGabi** [comment]
I'm just gonna give you write access to the repository

**Comment by MemeHovy** [comment]
> I'm just gonna give you write access to the repository

alright

**Comment by MemeHovy** [comment]
hey @BeastlyGabi I'm home now, so I'mma test this rq

**Review by MemeHovy — APPROVED** [review]

**Comment by MemeHovy** [comment]
thanks 👍🏻

**Pull request merged**
