### PR TITLE
Did things

### PR DESCRIPTION
**Pull request by MemeHoovy**
I don't think relying on a static var is a good idea in main (idk if this works, I winged it becuz codename engine & yoshicrafter is based)
And also removed useless shit & cleaned up code
and other things

### CODE REVIEW

**Comment by Wither362** [comment]
Hehehehehehe… _starts to sound creepy laught_
You haves changes  to do for Psych Engine didn’t you?

**Comment by Wither362** [comment]
I’m merging this when you resolve the conflicts I made to you, thanks Hoovity

**Comment by MemeHoovy** [comment]
> Hehehehehehe… _starts to sound creepy laught_ You haves changes to do for Psych Engine don’t you?

I can't .__.

**Comment by MemeHoovy** [comment]
> I’m merging this when you resolve the conflicts I made to you, thanks Hoovity

how? it says there's no conflicts

**Comment by Wither362** [comment]
> > I’m merging this when you resolve the conflicts I made to you, thanks Hoovity
> 
> how? it says there's no conflicts

With MY conflicts I meant "my pending changes"

**Comment by MemeHoovy** [comment]
well, I can't fix them if they're not on the repo

**Comment by MemeHoovy** [comment]
plus, I allowed edits from maintainers

**Comment by Wither362** [comment]
Ok, I will do them…

**Pull request merged**
