### PR TITLE
Update TODO.txt

### PR DESCRIPTION
**Pull request by XdgamerZ38**

### CODE REVIEW

**Comment by Wither362** [comment]
Isn’t it already done? Or are you making your own icon bounce?

**Comment by XdgamerZ38** [comment]
> Isn’t it already done? Or are you making your own icon bounce?

mine

**Comment by Wither362** [comment]
> > Isn’t it already done? Or are you making your own icon bounce?
> 
> mine

Ok, once you are done with it, tell it to me for me to push the code

**Comment by MemeHovy** [comment]
@XdgamerZ38 I might close theses PRs due to them being outdated as hell

**Comment by MemeHovy** [comment]
if you don't mind @Wither362

**Comment by Wither362** [comment]
Really, do what you want

**Comment by MemeHovy** [comment]
> Really, do what you want

alright

**Pull request closed without merging**
